version: '3.1'

services:

  wordpress: 
    build: . 
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    volumes: 
      - wp_uploads:/var/www/html/wp-content/uploads
      - wp_themes:/var/www/html/wp-content/themes
      - ./src/:/var/www/html/wp-content/plugins/source-recommendation

  db: 
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  adminer: 
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  wp_uploads:
  wp_themes:
  db:
  