version: '3.1'

services:
  wordpress: 
    build: . 
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes: 
      - wp_uploads:/var/www/html/wp-content/uploads
      - wp_themes:/var/www/html/wp-content/themes
      - ./src/:/var/www/html/wp-content/plugins/my-youtube-recommendation

  db: 
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: exampledb
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes: 
      - db:/var/lib/mysql

  adminer: 
    depends_on: 
      - db
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  wp_uploads:
  wp_themes:
  db:
